blog/urls.py
from django.contrib import admin
from django.urls import include, path

from blog import settings
from django.conf.urls.static import static

from panel.views.posts.views import PostDashboardListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('panel/',include('panel.urls')),
    path('',PostDashboardListView.as_view(),name='dashboard')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

panel/urls.py
from django.urls import path , include

urlpatterns = [
    path('users/',include('panel.views.users.urls')),
    path('posts/',include('panel.views.posts.urls')),
    path('comments/',include('panel.views.comments.urls')),
]

panel/views/comments/urls.py
from django.urls import path 
from .views import CommentListView, CommentCreateView , CommentDetailView, CommentUpdateView , CommentDeleteView 


app_name = 'comments'
urlpatterns = [
    path('',CommentListView.as_view(),name='list'),
    path('create',CommentCreateView.as_view(),name='create'),
    path('<int:pk>/update',CommentUpdateView.as_view(),name='update'),
    path('<int:pk>/detail',CommentDetailView.as_view(),name='detail'),
    path('<int:pk>/delete',CommentDeleteView.as_view(),name='delete'),
]

panel/views/posts/urls.py
from .views import PostCreateView, PostDeleteView, PostDetailView, PostUpdateView, PostListView
from django.urls import path 


app_name = 'post'
urlpatterns = [
    path('',PostListView.as_view(),name='list'),
    path('create',PostCreateView.as_view(),name='create'),
    path('<int:pk>/update',PostUpdateView.as_view(),name='update'),
    path('<int:pk>/detail',PostDetailView.as_view(),name='detail'),
    path('<int:pk>/delete',PostDeleteView.as_view(),name='delete'),
]

panel/views/users/urls.py
from django.urls import path
from .views import  UserCreateView, UserDeleteView, UserListView, UserProfileView, UserUpdateView 

app_name = 'users'
urlpatterns = [
    path('', UserListView.as_view(), name='list'),
    path('<int:pk>/', UserProfileView.as_view(), name='detail'),
    path('create/', UserCreateView.as_view(), name='create'),
    path('<int:pk>/update/', UserUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', UserDeleteView.as_view(), name='delete'),
]

panel/models.py
from django.db import models

# Create your models here.

panel/views/comments/forms.py
from django.forms import ModelForm, Select, Textarea

from post.models import Comment


class CommentsForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['post','content'] 
        widgets = {
            'post': Select(attrs={'class': 'form-select'}),
            "content": Textarea(attrs={'class':'form-control','placeholder':'یک کامنت بنویسید'})
        }

panel/views/posts/forms.py
from django import forms

from post.models import Post


class BlogForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','content','is_active']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control col-sm mb-3','placeholder':'عنوان'}),
            'content': forms.Textarea(attrs={'class': 'form-control','placeholder':'محتویات'}),
            'is_active': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

panel/views/users/forms.py
# forms.py
from django import forms
from django.contrib.auth import get_user_model
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field, HTML, Div
from crispy_forms.bootstrap import PrependedText

User = get_user_model()

class UserModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = ''  # Current URL
        
        # Add form layout
        self.helper.layout = Layout(
            Field('username', css_class='form-control'),
            Field('email', css_class='form-control'),
            Field('first_name', css_class='form-control'),
            Field('last_name', css_class='form-control'),
            Field('password', css_class='form-control'),
            
            Div(
                Submit('submit', '{% if object %}ذخیره تغییرات{% else %}ایجاد کاربر{% endif %}', 
                       css_class='btn btn-primary'),
                HTML('<a href="{% url \'users:list\' %}" class="btn btn-default">بازگشت</a>'),
                css_class='form-group text-left'
            )
        )
    
    def save(self, commit=True):
        user = super().save(commit=False)
        if self.cleaned_data['password']:
            user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

panel/views/comments/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from panel.views.comments.forms import CommentsForm
from post.models import Comment 
from django.views.generic import ListView, CreateView,UpdateView,View,DetailView
from django.shortcuts import get_object_or_404, redirect


class CommentListView(LoginRequiredMixin,PermissionRequiredMixin,ListView):
    model = Comment 
    template_name = 'panel/comments/list.html'
    context_object_name = 'comments'
    permission_required = ['post.view_comment']

class CommentCreateView(LoginRequiredMixin,PermissionRequiredMixin,CreateView):
    model = Comment
    template_name = 'panel/comments/create.html'
    form_class = CommentsForm
    permission_required = ['post.add_comment']
    success_url = reverse_lazy('comments:list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class CommentUpdateView(LoginRequiredMixin,PermissionRequiredMixin,UpdateView):
    model = Comment
    template_name = 'panel/comments/update.html'
    form_class = CommentsForm
    permission_required = ['post.change_comment']
    success_url = reverse_lazy('comments:list')

class CommentDetailView(LoginRequiredMixin,PermissionRequiredMixin,DetailView):
    model = Comment
    template_name = 'panel/comments/detail.html'
    form_class = CommentsForm 

    permission_required = ['post.view_comment']


class CommentDeleteView(LoginRequiredMixin,PermissionRequiredMixin,View):

    permission_required = ['post.delete_comment']
    def get(self,request,pk,**kwargs):
        obj = get_object_or_404(Comment,pk=pk)
        obj.delete()

        return redirect(reverse_lazy('comments:list'))

panel/views/posts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView, View
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from post.models import Comment, Post
from panel.views.posts.forms import BlogForm

class PostListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Post
    template_name = 'panel/posts/list.html'
    context_object_name = 'posts'
    permission_required = ['post.view_post']

class PostCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Post
    template_name = 'panel/posts/create.html'
    form_class = BlogForm
    success_url = reverse_lazy('post:list')
    permission_required = ['post.add_post']
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Post
    template_name = 'panel/posts/create.html'
    form_class = BlogForm
    success_url = reverse_lazy('post:list')
    permission_required = ['post.change_post']

class PostDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Post 
    template_name = 'panel/posts/detail.html'
    form_class = BlogForm
    context_object_name = 'post'
    permission_required = ['post.view_post']
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(post=self.object)
        return context

class PostDeleteView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = ['post.delete_post']
    
    def get(self, request, pk, **kwargs):
        obj = get_object_or_404(Post, pk=pk)
        obj.delete()
        return redirect(reverse_lazy('post:list'))

class PostDashboardListView(LoginRequiredMixin,ListView):
    model = Post
    template_name = 'panel/posts/dashboard.html'      
    context_object_name = 'posts'
    ordering = ['-created_at']
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Annotate each post with its comments (like your DetailView)
        for post in context['posts']:
            post.comments_list = Comment.objects.filter(post=post)
        return context

panel/views/users/views.py
from django.http import request
from django.shortcuts import get_list_or_404, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView, View 
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.forms import UserCreationForm


from panel.views.users.forms import UserModelForm
from post.models import Comment, Post 


User = get_user_model()

class UserProfileView(LoginRequiredMixin,PermissionRequiredMixin,DetailView):
    model = User 
    template_name = 'panel/users/profile.html'
    context_object_name = 'user'
    permission_required = ['auth.view_user']
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.filter(user=self.object)
        context['comments'] = Comment.objects.filter(user=self.object)
        return context


class UserListView(LoginRequiredMixin,PermissionRequiredMixin,ListView):
    model = User 
    template_name = 'panel/users/list.html'
    context_object_name = 'users'
    permission_required = ['auth.view_user']

class UserCreateView(LoginRequiredMixin,PermissionRequiredMixin,CreateView):
    model = User
    form_class = UserModelForm
    template_name = 'panel/users/create.html'
    success_url = reverse_lazy('users:list')
    permission_required = ['auth.add_user']

class UserDeleteView(LoginRequiredMixin,PermissionRequiredMixin,View):
    permission_required = ['auth.delete_user']
    def get(self,request,pk):
        obj = get_object_or_404(User,pk=pk)
        obj.delete()

class UserUpdateView(LoginRequiredMixin,PermissionRequiredMixin,UpdateView):
    model = User 
    template_name = 'panel/users/create.html'
    form_class = UserModelForm
    permission_required = ['auth.change_user']
    success_url = reverse_lazy('users:list')

panel/templates/panel/comments/create.html
{% extends 'templates/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="mb-3">
        {{ form.post.label_tag }}
        {{ form.post }}
    </div>
    <div class="mb-3">
        {{ form.content.label_tag }}
        {{ form.content }}
    </div>
    <button type="submit" class="btn btn-primary">ارسال</button>
</form>
{% endblock content %}

panel/templates/panel/comments/detail.html
{% extends 'templates/base.html' %}
{% load static %}
{% block content %}
<div class="card-body">
  <div class="tab-content">
    <div class="active tab-pane" id="activity">
      {% for comment in comments %}
        <!-- Post -->
        <div class="post">

          <p>{{ comment.content }}</p>

          <p>
            <a href="#" class="link-black text-sm mr-2"><i class="fa fa-share mr-1"></i> اشتراک گذاری</a>
            <a href="#" class="link-black text-sm"><i class="fa fa-thumbs-o-up mr-1"></i> لایک</a>
            <span class="float-left">
              <a href="#" class="link-black text-sm">
                <i class="fa fa-comments-o mr-1"></i> نظر ({{ comment.replies.count }})
              </a>
            </span>
          </p>

          <input class="form-control form-control-sm" type="text" placeholder="نظر خود را وارد کنید">
        </div>
        <!-- /.post -->
      {% empty %}
        <p>هیچ نظری وجود ندارد.</p>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock content %}

panel/templates/panel/comments/list.html
{% extends 'templates/base.html' %}
{% load static %}
{% block content %}
<div class="card-body">
  <div class="tab-content">
    <div class="active tab-pane" id="activity">
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>پست</th>
            <th>کاربر</th>
            <th>تاریخ</th>
            <th>محتوا</th>
            <th>عملیات</th>
          </tr>
        </thead>
        <tbody>
          {% for comment in comments %}
          <tr>
            <td>
              <a href="{% url 'post:detail' pk=comment.post.pk %}">
                {{ comment.post.title }}
              </a>
            </td>
            <td>{{ comment.user.get_full_name|default:comment.user.username }}</td>
            <td>{{ comment.created_at|date:"d M Y H:i" }}</td>
            <td>{{ comment.content }}</td>
            <td>
              <!-- Operations: add buttons here -->
              <a href="{% url 'comments:delete' comment.pk %}" class="btn btn-danger btn-sm">
                <i class='left fa fa-trash'></i>
                حذف
              </a>

              <a href="{% url 'comments:update' comment.pk %}" class="btn btn-info btn-sm">
                <i class='left fa fa-edit'></i>
                ویرایش
              </a>
              <!-- Add more buttons like Edit, Approve, etc. -->
            </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="5" class="text-center">هیچ نظری وجود ندارد.</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock content %}

panel/templates/panel/comments/update.html
{% extends 'templates/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="mb-3">
        {{ form.post.label_tag }}
        {{ form.post }}
    </div>
    <div class="mb-3">
        {{ form.content.label_tag }}
        {{ form.content }}
    </div>
    <button type="submit" class="btn btn-primary">ارسال</button>
</form>
{% endblock content %}