blog/urls.py
from django.contrib import admin
from django.urls import include, path

from blog import settings
from django.conf.urls.static import static

from panel.views.posts.views import PostDashboardListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('panel/',include('panel.urls')),
    path('',PostDashboardListView.as_view(),name='dashboard')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

panel/urls.py
from django.urls import path , include

urlpatterns = [
    path('users/',include('panel.views.users.urls')),
    path('posts/',include('panel.views.posts.urls')),
    path('comments/',include('panel.views.comments.urls')),
]

panel/views/posts/urls.py
from .views import PostCreateView, PostDeleteView, PostDetailView, PostUpdateView, PostListView
from django.urls import path 


app_name = 'post'
urlpatterns = [
    path('',PostListView.as_view(),name='list'),
    path('create',PostCreateView.as_view(),name='create'),
    path('<int:pk>/update',PostUpdateView.as_view(),name='update'),
    path('<int:pk>/detail',PostDetailView.as_view(),name='detail'),
    path('<int:pk>/delete',PostDeleteView.as_view(),name='delete'),
]

panel/views/users/urls.py
from django.urls import path
from .views import  UserCreateView, UserDeleteView, UserListView, UserProfileView, UserUpdateView 

app_name = 'users'
urlpatterns = [
    path('', UserListView.as_view(), name='list'),
    path('<int:pk>/', UserProfileView.as_view(), name='detail'),
    path('create/', UserCreateView.as_view(), name='create'),
    path('<int:pk>/update/', UserUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', UserDeleteView.as_view(), name='delete'),
]

panel/models.py
from django.db import models

# Create your models here.

panel/views/comments/forms.py
from django.forms import ModelForm, Select, Textarea

from post.models import Comment


class CommentsForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['post','content'] 
        widgets = {
            'post': Select(attrs={'class': 'form-select'}),
            "content": Textarea(attrs={'class':'form-control','placeholder':'یک کامنت بنویسید'})
        }

panel/views/posts/forms.py
from django import forms

from post.models import Post


class BlogForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','content','is_active']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control col-sm mb-3','placeholder':'عنوان'}),
            'content': forms.Textarea(attrs={'class': 'form-control','placeholder':'محتویات'}),
            'is_active': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

panel/views/users/forms.py
# forms.py
from django import forms
from django.contrib.auth import get_user_model
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field, HTML, Div
from crispy_forms.bootstrap import PrependedText

User = get_user_model()

class UserModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = ''  # Current URL
        
        # Add form layout
        self.helper.layout = Layout(
            Field('username', css_class='form-control'),
            Field('email', css_class='form-control'),
            Field('first_name', css_class='form-control'),
            Field('last_name', css_class='form-control'),
            Field('password', css_class='form-control'),
            
            Div(
                Submit('submit', '{% if object %}ذخیره تغییرات{% else %}ایجاد کاربر{% endif %}', 
                       css_class='btn btn-primary'),
                HTML('<a href="{% url \'users:list\' %}" class="btn btn-default">بازگشت</a>'),
                css_class='form-group text-left'
            )
        )
    
    def save(self, commit=True):
        user = super().save(commit=False)
        if self.cleaned_data['password']:
            user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

panel/views/comments/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from panel.views.comments.forms import CommentsForm
from post.models import Comment 
from django.views.generic import ListView, CreateView,UpdateView,View,DetailView
from django.shortcuts import get_object_or_404, redirect


class CommentListView(LoginRequiredMixin,PermissionRequiredMixin,ListView):
    model = Comment 
    template_name = 'panel/comments/list.html'
    context_object_name = 'comments'
    permission_required = ['post.view_comment']

class CommentCreateView(LoginRequiredMixin,PermissionRequiredMixin,CreateView):
    model = Comment
    template_name = 'panel/comments/create.html'
    form_class = CommentsForm
    permission_required = ['post.add_comment']
    success_url = reverse_lazy('comments:list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class CommentUpdateView(LoginRequiredMixin,PermissionRequiredMixin,UpdateView):
    model = Comment
    template_name = 'panel/comments/update.html'
    form_class = CommentsForm
    permission_required = ['post.change_comment']
    success_url = reverse_lazy('comments:list')

class CommentDetailView(LoginRequiredMixin,PermissionRequiredMixin,DetailView):
    model = Comment
    template_name = 'panel/comments/detail.html'
    form_class = CommentsForm 

    permission_required = ['post.view_comment']


class CommentDeleteView(LoginRequiredMixin,PermissionRequiredMixin,View):

    permission_required = ['post.delete_comment']
    def get(self,request,pk,**kwargs):
        obj = get_object_or_404(Comment,pk=pk)
        obj.delete()

        return redirect(reverse_lazy('comments:list'))

panel/views/posts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView, View
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from post.models import Comment, Post
from panel.views.posts.forms import BlogForm

class PostListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Post
    template_name = 'panel/posts/list.html'
    context_object_name = 'posts'
    permission_required = ['post.view_post']

class PostCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Post
    template_name = 'panel/posts/create.html'
    form_class = BlogForm
    success_url = reverse_lazy('post:list')
    permission_required = ['post.add_post']
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Post
    template_name = 'panel/posts/create.html'
    form_class = BlogForm
    success_url = reverse_lazy('post:list')
    permission_required = ['post.change_post']

class PostDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Post 
    template_name = 'panel/posts/detail.html'
    form_class = BlogForm
    context_object_name = 'post'
    permission_required = ['post.view_post']
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(post=self.object)
        return context

class PostDeleteView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = ['post.delete_post']
    
    def get(self, request, pk, **kwargs):
        obj = get_object_or_404(Post, pk=pk)
        obj.delete()
        return redirect(reverse_lazy('post:list'))

class PostDashboardListView(LoginRequiredMixin,ListView):
    model = Post
    template_name = 'panel/posts/dashboard.html'      
    context_object_name = 'posts'
    ordering = ['-created_at']
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Annotate each post with its comments (like your DetailView)
        for post in context['posts']:
            post.comments_list = Comment.objects.filter(post=post)
        return context

panel/views/users/views.py
from django.http import request
from django.shortcuts import get_list_or_404, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView, View 
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.forms import UserCreationForm


from panel.views.users.forms import UserModelForm
from post.models import Comment, Post 


User = get_user_model()

class UserProfileView(LoginRequiredMixin,PermissionRequiredMixin,DetailView):
    model = User 
    template_name = 'panel/users/profile.html'
    context_object_name = 'user'
    permission_required = ['auth.view_user']
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.filter(user=self.object)
        context['comments'] = Comment.objects.filter(user=self.object)
        return context


class UserListView(LoginRequiredMixin,PermissionRequiredMixin,ListView):
    model = User 
    template_name = 'panel/users/list.html'
    context_object_name = 'users'
    permission_required = ['auth.view_user']

class UserCreateView(LoginRequiredMixin,PermissionRequiredMixin,CreateView):
    model = User
    form_class = UserModelForm
    template_name = 'panel/users/create.html'
    success_url = reverse_lazy('users:list')
    permission_required = ['auth.add_user']

class UserDeleteView(LoginRequiredMixin,PermissionRequiredMixin,View):
    permission_required = ['auth.delete_user']
    def get(self,request,pk):
        obj = get_object_or_404(User,pk=pk)
        obj.delete()

class UserUpdateView(LoginRequiredMixin,PermissionRequiredMixin,UpdateView):
    model = User 
    template_name = 'panel/users/create.html'
    form_class = UserModelForm
    permission_required = ['auth.change_user']
    success_url = reverse_lazy('users:list')

panel/templates/panel/users/create.html
{% extends 'templates/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{% if object %}ویرایش کاربر{% else %}ایجاد کاربر جدید{% endif %}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="{% url 'users:list' %}">مدیریت کاربران</a></li>
                        <li class="breadcrumb-item active">{% if object %}ویرایش{% else %}ایجاد{% endif %}</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8 mx-auto">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">{% if object %}ویرایش کاربر{% else %}ایجاد کاربر جدید{% endif %}</h3>
                        </div>
                        
                        <div class="card-body">
                            {% if form.non_field_errors %}
                            <div class="alert alert-danger">
                                {{ form.non_field_errors }}
                            </div>
                            {% endif %}
                            
                            {{ form.media }}
                            
                            <!-- Use crispy form tag instead of wrapping in form tag -->
                            {% crispy form %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

{% endblock content %}

panel/templates/panel/users/list.html
{% extends 'templates/base.html' %}

{% block content %}
<div class="col-12">
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">لیست کاربران</h3>
    </div>
    <div class="card-body">
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>آیدی</th>
            <th>نام کاربری</th>
            <th>ایمیل</th>
            <th>عملیات</th>
          </tr>
        </thead>
        <tbody>
          {% for user in users %}
          <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.email }}</td>
            <td>
              {% if perms.auth.change_user %}
              <a href="{% url 'users:update' pk=user.pk %}" class="btn btn-info btn-sm">ویرایش</a>
              {% endif %}

              {% if perms.auth.view_user %}
              <a href="{% url 'users:detail' pk=user.pk %}" class="btn btn-secondary btn-sm">مشاهده</a>
              {% endif %}

              {% if perms.auth.delete_user %}
                <a href="{% url 'users:delete' pk=user.pk %}"  class="btn btn-danger btn-sm">حذف</a>
              {% endif %}
            </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="4">هیچ کاربری وجود ندارد</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock content %}

panel/templates/panel/users/profile.html
{% extends "templates/base.html" %}

{% block content %}
<section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-3">

            <!-- Profile Image -->
            <div class="card card-primary card-outline">
              <div class="card-body box-profile">
                <div class="text-center">
                  <img class="profile-user-img img-fluid img-circle" src="../../dist/img/user4-128x128.jpg" alt="User profile picture">
                </div>

                <h3 class="profile-username text-center">{{ user.get_full_name}}</h3>

                <p class="text-muted text-center">مهندس نرم افزار</p>

                <ul class="list-group list-group-unbordered mb-3">
                  <li class="list-group-item">
                    {{ user.created_at }}
                  </li>
                </ul>

              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <!-- About Me Box -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">درباره من</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <strong><i class="fa fa-book mr-1"></i> تحصیلات</strong>

                <p class="text-muted">
                  لیسانس نرم افزار کامپیوتر
                </p>

                <hr>

                <strong><i class="fa fa-file-alt mr-1"></i> یادداشت</strong>

                <p class="text-muted">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.</p>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
          <div class="col-md-9">
            <div class="card">
              <div class="card-header p-2">
                <ul class="nav nav-pills">
                  <li class="nav-item"><a class="nav-link active" href="#activity" data-toggle="tab">پست ها</a></li>
                  <li class="nav-item"><a class="nav-link" href="#comments" data-toggle="tab">نظرات</a></li>
                </ul>
              </div><!-- /.card-header -->
              <div class="card-body">
                <div class="tab-content">
                  <!-- Posts Tab -->
                  <div class="active tab-pane" id="activity">
                    {% for post in posts %}
                    <div class="post clearfix">
                      <div class="user-block">
                        <img class="img-circle img-bordered-sm" src="../../dist/img/user4-128x128.jpg" alt="user image">
                        <span class="username">
                          <a href="{% url 'post:detail' pk=post.pk%}">{{ post.title }}</a>
                          <a href="#" class="float-right btn-tool"><i class="fa fa-times"></i></a>
                        </span>
                        <span class="description">منتشر شده در {{ post.created_at }}</span>
                      </div>
                      <!-- /.user-block -->
                      <p>
                        {{ post.content }}
                      </p>

                      <p>
                        <a href="#" class="link-black text-sm mr-2">
                          <i class="fa fa-share mr-1"></i> اشتراک گذاری
                        </a>
                        <a href="#" class="link-black text-sm">
                          <i class="far fa-thumbs-up mr-1"></i> پسندیدن
                        </a>
                        <span class="float-right">
                          <a href="#" class="link-black text-sm">
                          </a>
                        </span>
                      </p>

                    </div>
                    <!-- /.post -->
                    {% endfor %}
                  </div>
                  <!-- /.tab-pane -->

                  <!-- Comments Tab -->
                  <div class="tab-pane" id="comments">
                    {% for comment in comments %}
                    <div class="post">
                      <div class="user-block">
                        <img class="img-circle img-bordered-sm" src="../../dist/img/user4-128x128.jpg" alt="user image">
                        <span class="username">
                          <a href="#">{{ user.get_full_name}}</a>
                        </span>
                        <span class="description">نظر در {{ comment.created_at }}</span>
                      </div>
                      <!-- /.user-block -->
                      
                      <p class="text-sm text-muted mb-2">
                      <i class="far fa-file-alt mr-1"></i> پست: <a href="{% url 'post:detail' pk=comment.post.pk %}">{{ comment.post_title }}</a>
                      </p>

                      <p>
                        {{ comment.content }}
                      </p>

                      <p>
                      <a href="{% url 'post:detail' pk=comment.post.pk %}" class="link-black text-sm mr-2">
                          <i class="fa fa-link mr-1"></i> مشاهده پست
                        </a>
                      </p>
                    </div>
                    <!-- /.post -->
                    {% endfor %}
                  </div>
                  <!-- /.tab-pane -->
                </div>
                <!-- /.tab-content -->
              </div><!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
{% endblock content %}