blog/urls.py
from django.contrib import admin
from django.urls import include, path

from blog import settings
from django.conf.urls.static import static

from panel.views.posts.views import PostDashboardListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('panel/',include('panel.urls')),
    path('',PostDashboardListView.as_view(),name='dashboard')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

panel/urls.py
from django.urls import path , include

urlpatterns = [
    path('users/',include('panel.views.users.urls')),
    path('posts/',include('panel.views.posts.urls')),
    path('comments/',include('panel.views.comments.urls')),
]

panel/views/posts/urls.py
from .views import PostCreateView, PostDeleteView, PostDetailView, PostUpdateView, PostListView
from django.urls import path 


app_name = 'post'
urlpatterns = [
    path('',PostListView.as_view(),name='list'),
    path('create',PostCreateView.as_view(),name='create'),
    path('<int:pk>/update',PostUpdateView.as_view(),name='update'),
    path('<int:pk>/detail',PostDetailView.as_view(),name='detail'),
    path('<int:pk>/delete',PostDeleteView.as_view(),name='delete'),
]

panel/views/users/urls.py
from django.urls import path
from .views import  UserCreateView, UserDeleteView, UserListView, UserProfileView, UserUpdateView 

app_name = 'users'
urlpatterns = [
    path('', UserListView.as_view(), name='list'),
    path('<int:pk>/', UserProfileView.as_view(), name='detail'),
    path('create/', UserCreateView.as_view(), name='create'),
    path('<int:pk>/update/', UserUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', UserDeleteView.as_view(), name='delete'),
]

panel/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from django.contrib.auth import get_user_model 

User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User,on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=255)
    content = models.TextField() 

    is_active = models.BooleanField(default=True)
    updated_at = models.DateTimeField(auto_now=True) 
    created_at = models.DateTimeField(auto_now_add=True) 


class Comment(models.Model):
    user = models.ForeignKey(User,on_delete=models.DO_NOTHING)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)

    content = models.TextField() 
    is_active = models.BooleanField(default=True)
    updated_at = models.DateTimeField(auto_now=True) 
    created_at = models.DateTimeField(auto_now_add=True) 

panel/views/comments/forms.py
from django.forms import ModelForm, Select, Textarea

from post.models import Comment


class CommentsForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['post','content'] 
        widgets = {
            'post': Select(attrs={'class': 'form-select'}),
            "content": Textarea(attrs={'class':'form-control','placeholder':'یک کامنت بنویسید'})
        }

panel/views/posts/forms.py
from django import forms

from post.models import Post


class BlogForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','content','is_active']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control col-sm mb-3','placeholder':'عنوان'}),
            'content': forms.Textarea(attrs={'class': 'form-control','placeholder':'محتویات'}),
            'is_active': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

panel/views/users/forms.py
# forms.py
from django import forms
from django.contrib.auth import get_user_model
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field, HTML, Div
from crispy_forms.bootstrap import PrependedText

User = get_user_model()

class UserModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = ''  # Current URL
        
        # Add form layout
        self.helper.layout = Layout(
            Field('username', css_class='form-control'),
            Field('email', css_class='form-control'),
            Field('first_name', css_class='form-control'),
            Field('last_name', css_class='form-control'),
            Field('password', css_class='form-control'),
            
            Div(
                Submit('submit', '{% if object %}ذخیره تغییرات{% else %}ایجاد کاربر{% endif %}', 
                       css_class='btn btn-primary'),
                HTML('<a href="{% url \'users:list\' %}" class="btn btn-default">بازگشت</a>'),
                css_class='form-group text-left'
            )
        )
    
    def save(self, commit=True):
        user = super().save(commit=False)
        if self.cleaned_data['password']:
            user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

panel/views/comments/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from panel.views.comments.forms import CommentsForm
from post.models import Comment 
from django.views.generic import ListView, CreateView,UpdateView,View,DetailView
from django.shortcuts import get_object_or_404, redirect


class CommentListView(LoginRequiredMixin,PermissionRequiredMixin,ListView):
    model = Comment 
    template_name = 'panel/comments/list.html'
    context_object_name = 'comments'
    permission_required = ['post.view_comment']

class CommentCreateView(LoginRequiredMixin,PermissionRequiredMixin,CreateView):
    model = Comment
    template_name = 'panel/comments/create.html'
    form_class = CommentsForm
    permission_required = ['post.add_comment']
    success_url = reverse_lazy('comments:list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class CommentUpdateView(LoginRequiredMixin,PermissionRequiredMixin,UpdateView):
    model = Comment
    template_name = 'panel/comments/update.html'
    form_class = CommentsForm
    permission_required = ['post.change_comment']
    success_url = reverse_lazy('comments:list')

class CommentDetailView(LoginRequiredMixin,PermissionRequiredMixin,DetailView):
    model = Comment
    template_name = 'panel/comments/detail.html'
    form_class = CommentsForm 

    permission_required = ['post.view_comment']


class CommentDeleteView(LoginRequiredMixin,PermissionRequiredMixin,View):

    permission_required = ['post.delete_comment']
    def get(self,request,pk,**kwargs):
        obj = get_object_or_404(Comment,pk=pk)
        obj.delete()

        return redirect(reverse_lazy('comments:list'))

panel/views/posts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView, View
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from post.models import Comment, Post
from panel.views.posts.forms import BlogForm

class PostListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Post
    template_name = 'panel/posts/list.html'
    context_object_name = 'posts'
    permission_required = ['post.view_post']

class PostCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Post
    template_name = 'panel/posts/create.html'
    form_class = BlogForm
    success_url = reverse_lazy('post:list')
    permission_required = ['post.add_post']
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Post
    template_name = 'panel/posts/create.html'
    form_class = BlogForm
    success_url = reverse_lazy('post:list')
    permission_required = ['post.change_post']

class PostDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Post 
    template_name = 'panel/posts/detail.html'
    form_class = BlogForm
    context_object_name = 'post'
    permission_required = ['post.view_post']
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(post=self.object)
        return context

class PostDeleteView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = ['post.delete_post']
    
    def get(self, request, pk, **kwargs):
        obj = get_object_or_404(Post, pk=pk)
        obj.delete()
        return redirect(reverse_lazy('post:list'))

class PostDashboardListView(LoginRequiredMixin,ListView):
    model = Post
    template_name = 'panel/posts/dashboard.html'      
    context_object_name = 'posts'
    ordering = ['-created_at']
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Annotate each post with its comments (like your DetailView)
        for post in context['posts']:
            post.comments_list = Comment.objects.filter(post=post)
        return context

panel/views/users/views.py
from django.http import request
from django.shortcuts import get_list_or_404, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView, View 
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.forms import UserCreationForm


from panel.views.users.forms import UserModelForm
from post.models import Comment, Post 


User = get_user_model()

class UserProfileView(LoginRequiredMixin,PermissionRequiredMixin,DetailView):
    model = User 
    template_name = 'panel/users/profile.html'
    context_object_name = 'user'
    permission_required = ['auth.view_user']
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.filter(user=self.object)
        context['comments'] = Comment.objects.filter(user=self.object)
        return context


class UserListView(LoginRequiredMixin,PermissionRequiredMixin,ListView):
    model = User 
    template_name = 'panel/users/list.html'
    context_object_name = 'users'
    permission_required = ['auth.view_user']

class UserCreateView(LoginRequiredMixin,PermissionRequiredMixin,CreateView):
    model = User
    form_class = UserModelForm
    template_name = 'panel/users/create.html'
    success_url = reverse_lazy('users:list')
    permission_required = ['auth.add_user']

class UserDeleteView(LoginRequiredMixin,PermissionRequiredMixin,View):
    permission_required = ['auth.delete_user']
    def get(self,request,pk):
        obj = get_object_or_404(User,pk=pk)
        obj.delete()

class UserUpdateView(LoginRequiredMixin,PermissionRequiredMixin,UpdateView):
    model = User 
    template_name = 'panel/users/create.html'
    form_class = UserModelForm
    permission_required = ['auth.change_user']
    success_url = reverse_lazy('users:list')

post/views.py
from django.shortcuts import render

# Create your views here.

panel/templates/panel/posts/create.html
{% extends 'templates/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">مثال ساده</h3>
        </div>

        <form method="POST" role="form">
          {% csrf_token %}
          <div class="card-body">

            <div class="form-group">
              {{ form.title }}
              {{ form.content }}
            </div>

            <div class="form-check mt-2">
              {{ form.is_active }}
              <label class="form-check-label" for="{{ form.is_active.id_for_label }}">
                دیده شود
              </label>
              {% if form.is_active.errors %}
              <div class="text-danger">{{ form.is_active.errors }}</div>
              {% endif %}
            </div>

          </div>

          <div class="card-footer text-center">
            <button type="submit" class="btn btn-primary px-4">ثبت</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

panel/templates/panel/posts/dashboard.html
{% extends 'templates/base.html' %}
{% block content %}
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-3">
            <div class="col-sm-6">
                <h1 class="m-0">پست‌های داشبورد</h1>
            </div>
        </div>
    </div>
</div>

<section class="content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                {% for post in posts %}
                <div class="card mb-4 shadow-sm">
                    <div class="card-header bg-light">
                        <div class="d-flex justify-content-between align-items-center">
                            <span class="fw-bold">{{ post.user.username }}</span>
                            <small class="text-muted">منتشر شده در {{ post.created_at|date:"Y/m/d - H:i" }}</small>
                        </div>
                    </div>
                    <div class="card-body">
            <h4 class="card-title mb-2"><a href="{% url 'post:detail' pk=post.pk %}">{{ post.title }}</a></h4>
                        <p class="card-text">{{ post.content|truncatewords:40 }}</p>
                    </div>

                    <div class="card-footer bg-white border-top">
                        <h6 class="text-muted mb-2">
                            <i class="far fa-comments me-1"></i> نظرات ({{ post.comments_list|length }})
                        </h6>
                        {% if post.comments_list %}
                            <ul class="list-unstyled mb-0">
                                {% for comment in post.comments_list %}
                                <li class="mb-2 pb-2 border-bottom">
                                    <small class="text-muted d-block">{{ comment.user.username }} – {{ comment.created_at|date:"Y/m/d H:i" }}</small>
                                    <p class="mb-0 mt-1">{{ comment.content|truncatewords:20 }}</p>
                                </li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <p class="text-muted mb-0">نظری ثبت نشده است.</p>
                        {% endif %}
                    </div>
                </div>
                {% empty %}
                <div class="alert alert-info text-center">
                    <h5><i class="fas fa-info-circle me-1"></i> پستی وجود ندارد</h5>
                    <p class="mb-0">هیچ پستی برای نمایش وجود ندارد.</p>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

panel/templates/panel/posts/detail.html
{% extends 'templates/base.html' %}
{% block content %}
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">جزئیات پست</h1>
            </div>
        </div>
    </div>
</div>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <!-- Post Detail -->
                <div class="card card-widget">
                    <div class="card-header">
                        <div class="user-block">
                            <img class="img-circle" src="../../dist/img/user4-128x128.jpg" alt="User Image">
                            <span class="username"><a href="#">{{ post.user.username }}</a></span>
                            <span class="description">منتشر شده در {{ post.created_at|date:"Y/m/d - H:i" }}</span>
                        </div>
                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" title="نشان کردن">
                                <i class="far fa-star"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        <h4 class="mb-3"><strong>{{ post.title }}</strong></h4>
                        <p class="lead">{{ post.content }}</p>
                        
                        <p class="text-sm text-muted">
                            <i class="far fa-clock"></i> آخرین بروزرسانی: {{ post.updated_at|date:"Y/m/d - H:i" }}
                        </p>
                    </div>
                    <div class="card-footer card-comments" style="display: block;">
                        <div class="card-comment">
                            <div class="comment-text">
                                <span class="username text-muted">
                                    <i class="fas fa-eye ml-1"></i> بازدید ها
                                    <span class="text-sm float-right">۱۲۳ بازدید</span>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card -->

                <!-- Comments Section (List Style) -->
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">
                            <i class="fas fa-comments"></i> نظرات
                        </h3>
                        <div class="card-tools">
                            <span class="badge badge-primary">{{ comments.count }}</span>
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        {% if comments %}
                            <ul class="list-group list-group-flush">
                                {% for comment in comments %}
                                <li class="list-group-item">
                                    <div class="d-flex justify-content-between">
                                        <strong>{{ comment.user.username }}</strong>
                                        <small class="text-muted">{{ comment.created_at|date:"Y/m/d - H:i" }}</small>
                                    </div>
                                    <p class="mt-2 mb-0">{{ comment.content }}</p>
                                </li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <div class="callout callout-info">
                                <h5><i class="icon fas fa-info"></i> نظری وجود ندارد</h5>
                                <p class="mb-0">هنوز نظری برای این پست ثبت نشده است. اولین نفری باشید که نظر می‌دهید!</p>
                            </div>
                        {% endif %}
                    </div>
                    {% if comments %}
                    <div class="card-footer">
                        <div class="info-box mb-0 bg-light">
                            <span class="info-box-icon bg-info"><i class="far fa-comments"></i></span>
                            <div class="info-box-content">
                                <span class="info-box-text">مجموع نظرات</span>
                                <span class="info-box-number">{{ comments.count }}</span>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div>
</section>
{% endblock %}

panel/templates/panel/posts/list.html
{% extends 'templates/base.html' %}

{% block content %} 
<div class="col-12">
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">Posts List</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
      <div id="example1_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <div class="dataTables_length" id="example1_length">
              <label>
                Show 
                <select name="example1_length" aria-controls="example1" class="form-control form-control-sm">
                  <option value="10">10</option>
                  <option value="25">25</option>
                  <option value="50">50</option>
                  <option value="100">100</option>
                </select> 
                entries
              </label>
            </div>
          </div>
          <div class="col-sm-12 col-md-6">
            <div id="example1_filter" class="dataTables_filter">
              <label>Search:
                <input type="search" class="form-control form-control-sm" placeholder="" aria-controls="example1">
              </label>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
            <table id="example1" class="table table-bordered table-striped dataTable" role="grid">
              <thead>
                <tr>
                  <th>شماره پست</th>
                  <th>تایتل</th>
                  <th>عملیات</th>
                </tr>
              </thead>
              <tbody>
                {% for post in posts %}
                  <tr role="row" class="{% cycle 'odd' 'even' %}">
                    <td>{{ post.id }}</td>
                    {% if perms.post.view_post %}
                    <td>
                      <a href="{% url 'post:detail' pk=post.pk %}">{{ post.title }}</a>
                    </td>
                    {% endif %}
                    <td style="width: 20px;">

                    {% if perms.post.delete_post %}
                      <a href="{% url 'post:delete' pk=post.pk %}" class="btn btn-block btn-danger btn-sm">
                        <i class="left fa fa-trash"></i> حذف
                      </a>
                    {% endif %}

                    {% if perms.post.change_post %}
                      <a href="{% url 'post:update' pk=post.pk %}" class="btn btn-block btn-info btn-sm">
                        <i class="left fa fa-edit"></i> ویرایش
                      </a>
                    {% endif %} 
                    {% if perms.post.view_post %}
                      <a href="{% url 'post:detail' pk=post.pk %}" class="btn btn-block btn-secondary btn-sm">
                        <i class="left fa fa-eye"></i> مشاهده
                      </a>
                    {% endif %}
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>


      </div>
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
</div>
{% endblock content %}

panel/templates/panel/posts/update.html
{% extends 'templates/base.html' %}

{% block content %}
<div class="col-md-6">
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">مثال ساده</h3>
        </div>

        <form method="POST" role="form">
            {% csrf_token %}
            <div class="card-body">

                <div class="form-group">

                    {{form.title }}
                    {{form.content }}
                </div>

                <div class="form-check">
                    {{ form.is_active }}
                    دیده شود
                    {% if form.is_active.errors %}
                        <div class="text-danger">{{ form.is_active.errors }}</div>
                    {% endif %}
                </div>
                <a href="{% url 'post:delete' pk=post.pk %}" class="btn btn-block btn-danger btn-sm">
                  پاک کردن پست
                </a>

            </div>

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">ثبت</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}