blog/urls.py
from django.contrib import admin
from django.urls import include, path

from blog import settings
from django.conf.urls.static import static

from panel.views.posts.views import PostDashboardListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('panel/',include('panel.urls')),
    path('',PostDashboardListView.as_view(),name='dashboard')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

panel/views/comments/urls.py
from django.urls import path 
from .views import CommentListView, CommentCreateView , CommentDetailView, CommentUpdateView , CommentDeleteView 


app_name = 'comments'
urlpatterns = [
    path('',CommentListView.as_view(),name='list'),
    path('create',CommentCreateView.as_view(),name='create'),
    path('<int:pk>/update',CommentUpdateView.as_view(),name='update'),
    path('<int:pk>/detail',CommentDetailView.as_view(),name='detail'),
    path('<int:pk>/delete',CommentDeleteView.as_view(),name='delete'),
]

panel/views/posts/urls.py
from .views import PostCreateView, PostDeleteView, PostDetailView, PostUpdateView, PostListView
from django.urls import path 


app_name = 'post'
urlpatterns = [
    path('',PostListView.as_view(),name='list'),
    path('create',PostCreateView.as_view(),name='create'),
    path('<int:pk>/update',PostUpdateView.as_view(),name='update'),
    path('<int:pk>/detail',PostDetailView.as_view(),name='detail'),
    path('<int:pk>/delete',PostDeleteView.as_view(),name='delete'),
]

panel/views/users/urls.py
from django.urls import path
from .views import  UserCreateView, UserDeleteView, UserListView, UserProfileView, UserUpdateView 

app_name = 'users'
urlpatterns = [
    path('', UserListView.as_view(), name='list'),
    path('<int:pk>/', UserProfileView.as_view(), name='detail'),
    path('create/', UserCreateView.as_view(), name='create'),
    path('<int:pk>/update/', UserUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', UserDeleteView.as_view(), name='delete'),
]

post/models.py
from django.db import models
from django.contrib.auth import get_user_model 

User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User,on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=255)
    content = models.TextField() 

    is_active = models.BooleanField(default=True)
    updated_at = models.DateTimeField(auto_now=True) 
    created_at = models.DateTimeField(auto_now_add=True) 


class Comment(models.Model):
    user = models.ForeignKey(User,on_delete=models.DO_NOTHING)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)

    content = models.TextField() 
    is_active = models.BooleanField(default=True)
    updated_at = models.DateTimeField(auto_now=True) 
    created_at = models.DateTimeField(auto_now_add=True) 

templates/inc/_partials/sidebar.html
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="https://www.gravatar.com/avatar/52f0fbcbedee04a121cba8dad1174462?s=200&d=mm&r=g"
             class="img-circle elevation-2"
             alt="User Image">
      </div>
      <div class="info">
        <a href="#" class="d-block">حسام موسوی</a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        {% if perms.post.view_post %}
          <!-- Blog Treeview -->
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fa fa-dashboard"></i>
              <p>
                بلاگ
                <i class="right fa fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'post:list' %}" class="nav-link">
                  <i class="fa fa-list nav-icon"></i>
                  <p>لیست مطالب</p>
                </a>
              </li>
              {% if perms.post.add_post %}
              <li class="nav-item">
                <a href="{% url 'post:create' %}" class="nav-link">
                  <i class="fa fa-plus nav-icon"></i>
                  <p>ساخت پست</p>
                </a>
              </li>
              {% endif %}
            </ul>
          </li>
          {% endif %}
        {% if perms.auth.view_user %}
        <li class="nav-item has-treeview">
          <a href="#" class="nav-link">
            <i class="nav-icon fa fa-users"></i>
            <p>
              کاربران
              <i class="right fa fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'users:list'%}" class="nav-link">
                <i class="fa fa-users nav-icon"></i>
                <p>لیست کاربران</p>
              </a>
            </li>


          {% if perms.auth.add_user %}
            <li class="nav-item">
              <a href="{% url 'users:create' %}" class="nav-link">
                <i class="fa fa-user nav-icon"></i>
                <p>ایجاد کاربر</p>
              </a>
            </li>
          {% endif %}
          </ul>
        </li>
        {% endif %}

        {% if perms.post.view_comment %}

          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fa fa-envelope"></i>
              <p>
                کامنت ها 
                <i class="right fa fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'comments:list' %}" class="nav-link">
                  <i class="fa fa-bars nav-icon"></i>
                  <p>لیست کامنت ها</p>
                </a>
              </li>


            {% if perms.post.create_comment %}
              <li class="nav-item">
                <a href="{% url 'comments:create' %}" class="nav-link">
                  <i class="fa fa-user nav-icon"></i>
                  <p>ایجاد کامنت</p>
                </a>
              </li>
            </ul>
          </li>
          {% endif %}
        {% endif %}
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>